export interface LegalSection {
  title: string;
  paragraphs?: readonly string[];
  bullets?: readonly string[];
}

export interface LegalDocument {
  title: string;
  description: string;
  sections: readonly LegalSection[];
}

export const termsDocument: LegalDocument = {
  title: "Terms of Service",
  description: "The terms governing access to the Vireonix website and the delivery of our IT and digital services.",
  sections: [
    { title: "Who We Are", paragraphs: ["Vireonix (“we”, “us”, “our”) is an IT and digital solutions brand operating from Zurich, Switzerland. We provide technology and digital services including web development, app development, AI/ML solutions, cybersecurity, SEO, digital marketing, graphic design, branding, SaaS development, custom software development, software testing, cloud solutions, automation, chatbot development, and IT consulting.", "These Terms of Service govern your access to our website, vireonix.dev, and your use of our services.", "Any formal project, invoice, or agreement may include additional contracting details agreed directly with the client."] },
    { title: "Scope of Services", paragraphs: ["Vireonix provides digital and technology-related services based on client requirements, project scope, proposals, and written agreements. Services may include design, development, consulting, optimization, maintenance, support, and other IT-related work.", "The exact scope, deliverables, timeline, revisions, pricing, and payment terms for each project will be agreed separately through a proposal, invoice, quotation, email confirmation, or written agreement."] },
    { title: "Quotes, Pricing & Payment", paragraphs: ["All prices, quotations, and estimates are based on the project requirements shared by the client. Pricing may change if the scope, timeline, features, content, integrations, or technical complexity changes.", "Unless otherwise agreed, work may begin after confirmation of the project and receipt of any required advance payment. Remaining payments must be made according to the agreed milestones, invoice terms, or project agreement.", "Vireonix reserves the right to pause work, delay delivery, or withhold final files, deployment, credentials, or handover until outstanding payments are cleared."] },
    { title: "Client Responsibilities", paragraphs: ["The client agrees to provide accurate information, required content, brand assets, access credentials, approvals, feedback, and any other material necessary for project completion.", "Delays in providing required information, approvals, payments, or access may affect the project timeline. Vireonix will not be responsible for delays caused by incomplete, incorrect, or late client input."] },
    { title: "Revisions & Scope Changes", paragraphs: ["Revisions are included only as agreed in the project scope. Any additional changes, new features, redesigns, extra pages, integrations, or work outside the approved scope may be charged separately.", "Vireonix will inform the client before proceeding with any major out-of-scope work."] },
    { title: "Delivery Timelines", paragraphs: ["Project timelines are estimates unless specifically confirmed as fixed deadlines in writing. Timelines may be affected by client feedback delays, technical issues, third-party services, hosting problems, domain/DNS delays, API limitations, payment delays, or changes in project scope."] },
    { title: "Third-Party Services", paragraphs: ["Projects may require third-party services such as hosting providers, domain registrars, payment gateways, analytics tools, email platforms, APIs, plugins, software libraries, or cloud services.", "Vireonix is not responsible for downtime, pricing changes, limitations, policy changes, security issues, or service interruptions caused by third-party providers. Any third-party fees are the client’s responsibility unless otherwise agreed."] },
    { title: "Intellectual Property", paragraphs: ["After full payment is received, the client will own the final custom deliverables created specifically for their project, unless otherwise agreed.", "Vireonix retains ownership of its pre-existing code, tools, frameworks, design systems, templates, internal processes, reusable components, know-how, and general technical methods.", "The client must ensure that any content, images, logos, text, fonts, or media provided to Vireonix are legally owned or properly licensed."] },
    { title: "Portfolio Rights", paragraphs: ["Unless otherwise agreed in writing, Vireonix may display completed work, project names, website links, screenshots, and general project descriptions in its portfolio, case studies, social media, and marketing material.", "Confidential or sensitive project details will not be shared without permission."] },
    { title: "Confidentiality", paragraphs: ["Vireonix will take reasonable care to protect confidential client information, project details, credentials, and business data. The client should avoid sharing unnecessary sensitive information unless required for the project."] },
    { title: "Website Content & SEO", paragraphs: ["Vireonix may provide SEO, marketing, content, or optimization services, but we do not guarantee specific rankings, traffic numbers, sales, leads, revenue, or search engine positions. Search engines, advertising platforms, and social media platforms use independent algorithms and policies beyond our control."] },
    { title: "Cybersecurity & Technical Services", paragraphs: ["Vireonix may provide cybersecurity-related services such as audits, recommendations, security improvements, monitoring setup, or best-practice implementation. However, no system can be guaranteed to be completely secure. The client remains responsible for maintaining secure passwords, access controls, software updates, backups, and internal security practices."] },
    { title: "Limitation of Liability", paragraphs: ["To the maximum extent permitted by applicable law, Vireonix will not be liable for indirect, incidental, special, consequential, or business losses, including loss of profits, loss of revenue, loss of data, downtime, missed opportunities, or damage caused by third-party services.", "Our total liability for any project is limited to the amount paid by the client for the specific service giving rise to the claim."] },
    { title: "Termination", paragraphs: ["Either party may terminate a project according to the agreed terms. If a project is cancelled after work has started, the client may be responsible for payment for completed work, time spent, third-party costs, and any non-refundable expenses."] },
    { title: "Privacy", paragraphs: ["We process personal information according to our Privacy Policy, available on our website."] },
    { title: "Governing Law", paragraphs: ["These Terms are governed by the laws applicable to the agreed client relationship and project arrangement. Where no separate written agreement applies, disputes will be handled through good-faith negotiation first."] },
    { title: "Changes to These Terms", paragraphs: ["We may update these Terms from time to time. The updated version will be posted on this page with a new “Last updated” date."] },
    { title: "Contact", paragraphs: ["For questions about these Terms, contact us at contact@vireonix.dev or through https://vireonix.dev. Vireonix operates from Zurich, Switzerland."] },
  ],
};

export const privacyDocument: LegalDocument = {
  title: "Privacy Policy",
  description: "How Vireonix collects, uses, stores, shares, and protects personal information.",
  sections: [
    { title: "Overview", paragraphs: ["This Privacy Policy explains how Vireonix (“we”, “us”, “our”) collects, uses, stores, and protects personal information when you visit our website, contact us, request a quote, or use our services.", "We are committed to handling personal information responsibly and transparently. Where applicable, we aim to follow recognized privacy principles, including lawful processing, data minimization, security, transparency, and user control."] },
    { title: "Information We Collect", paragraphs: ["Contact Information: Name, email address, phone number, company name, job title, and other contact details.", "Project Information: Information you provide about your business, project requirements, budget, timeline, goals, existing website, technical needs, or service preferences.", "Communication Data: Messages, emails, forms, meeting notes, support requests, and feedback you send to us.", "Technical Data: IP address, browser type, device type, operating system, pages visited, referral source, approximate location, and website usage data.", "Payment & Billing Data: Billing details, invoice information, payment status, and transaction references. If online payments are used, payment card details are processed by third-party payment providers and are not stored by Vireonix.", "Marketing & Analytics Data: Information about how visitors interact with our website, campaigns, social media, or advertisements, where such tools are used."] },
    { title: "How We Collect Information", paragraphs: ["We collect information when you:"], bullets: ["visit our website", "fill out a contact form", "request a quote or consultation", "email or message us", "book a meeting", "use our services", "interact with our social media or advertisements", "provide project files, credentials, or business information", "use website features that rely on cookies or analytics"] },
    { title: "How We Use Information", paragraphs: ["We use personal information to:"], bullets: ["respond to inquiries", "provide quotes and proposals", "deliver IT and digital services", "communicate about projects", "manage client relationships", "provide support and maintenance", "improve our website and services", "process invoices and payments", "secure our website and systems", "prevent fraud or misuse", "send updates or marketing communications where permitted", "comply with legal, accounting, or business obligations"] },
    { title: "Legal Basis", paragraphs: ["Where a legal basis is required, we process information based on one or more of the following:"], bullets: ["performance of a contract or pre-contract steps", "your consent", "legitimate business interests", "legal or regulatory obligations", "protection of our rights, systems, users, or business"] },
    { title: "Cookies & Analytics", paragraphs: ["Our website may use cookies, analytics tools, tracking pixels, or similar technologies to improve performance, understand visitor behavior, measure marketing campaigns, and improve user experience.", "If we use non-essential cookies or marketing tracking, we will request consent through a cookie banner where required.", "Users can control cookies through browser settings."] },
    { title: "Sharing of Information", paragraphs: ["We do not sell personal information.", "We may share information only when necessary with:"], bullets: ["hosting providers", "domain and email service providers", "analytics providers", "payment processors", "project management tools", "subcontractors or technical partners", "marketing or advertising platforms", "legal, accounting, or compliance advisors", "authorities where required by law"] },
    { title: "International Transfers", paragraphs: ["Because Vireonix may work with clients, tools, hosting providers, and vendors in different countries, information may be processed outside the user’s country.", "Where required, we aim to use appropriate safeguards and trusted service providers to protect personal information."] },
    { title: "Data Retention", paragraphs: ["We keep personal information only as long as necessary for the purposes described in this Policy.", "Typical retention periods may include:"], bullets: ["project and communication records: for the duration of the client relationship and a reasonable period afterward", "billing and invoice records: as required for accounting, tax, or legal purposes", "analytics data: for the shortest practical period needed for reporting and improvement", "support records: as long as needed to provide service and resolve issues"] },
    { title: "Data Security", paragraphs: ["We use reasonable technical and organizational measures to protect personal information, including access controls, secure communication, limited access, backups where appropriate, and responsible handling of credentials.", "However, no internet-based system is completely secure. Clients are responsible for keeping their own passwords, hosting accounts, domain accounts, and third-party credentials secure."] },
    { title: "Your Rights", paragraphs: ["Subject to applicable law, users may request to:"], bullets: ["access personal information", "correct inaccurate information", "delete certain information", "restrict or object to processing", "withdraw consent where processing is based on consent", "request a copy of certain information", "opt out of marketing communications"], },
    { title: "Marketing Communications", paragraphs: ["If users subscribe to updates or agree to receive marketing messages, we may contact them about Vireonix services, updates, offers, or content.", "Users can unsubscribe or opt out at any time by contacting us."] },
    { title: "Children’s Privacy", paragraphs: ["Our services are intended for businesses and individuals aged 18 or above. We do not knowingly collect personal information from children under 16. If we become aware that we have collected such information, we will take reasonable steps to delete it."] },
    { title: "Third-Party Links", paragraphs: ["Our website may contain links to third-party websites. We are not responsible for the privacy practices, content, or security of external websites."] },
    { title: "Changes to This Policy", paragraphs: ["We may update this Privacy Policy from time to time. The updated version will be posted on this page with a new “Last updated” date."] },
    { title: "Contact", paragraphs: ["To exercise privacy rights, we may need to verify your identity before processing a request. Contact contact@vireonix.dev or visit https://vireonix.dev. Vireonix operates from Zurich, Switzerland."] },
  ],
};

export const noticeDocument: LegalDocument = {
  title: "Legal Notice",
  description: "Operator information and important notices concerning the Vireonix website and its content.",
  sections: [
    { title: "Operator Information", paragraphs: ["Brand/Operator: Vireonix", "Business Type: IT & Digital Solutions", "Location: Zurich, Switzerland", "Website: https://vireonix.dev", "Email: contact@vireonix.dev", "This Legal Notice identifies Vireonix as the brand/operator of this website for contact transparency."] },
    { title: "Services", paragraphs: ["Vireonix provides IT and digital services including web development, app development, AI/ML solutions, cybersecurity, SEO, digital marketing, graphic design, branding, SaaS development, custom software development, software testing, cloud solutions, business automation, chatbot development, and IT consulting."] },
    { title: "Responsibility for Content", paragraphs: ["We prepare the content on this website with care. However, we do not guarantee that all information is complete, accurate, current, or suitable for every purpose.", "We may update, change, remove, or modify website content at any time without prior notice."] },
    { title: "External Links", paragraphs: ["This website may contain links to external websites. Vireonix has no control over the content, availability, security, or privacy practices of third-party websites.", "The respective owners or operators of external websites are responsible for their own content and policies."] },
    { title: "Copyright & Intellectual Property", paragraphs: ["All content on this website, including text, design, graphics, logos, layouts, images, icons, code, and other materials, is protected by copyright and intellectual property laws unless stated otherwise.", "Users may not copy, reproduce, distribute, modify, publish, or use any website content for commercial purposes without prior written permission from Vireonix."] },
    { title: "Brand & Logo", paragraphs: ["The Vireonix name, logo, tagline, visual identity, and brand assets belong to Vireonix. Unauthorized use of our brand assets is not permitted."] },
    { title: "No Professional Guarantee", paragraphs: ["Information on this website is provided for general business and informational purposes. It does not create a client relationship unless a project is formally agreed.", "Any technical, cybersecurity, SEO, marketing, or business recommendations provided by Vireonix depend on the project scope, available information, third-party platforms, and client implementation."] },
    { title: "Limitation of Liability", paragraphs: ["To the maximum extent permitted by applicable law, Vireonix is not responsible for losses resulting from use of this website, reliance on website content, third-party links, website downtime, technical errors, or external service interruptions."] },
    { title: "Updates to This Notice", paragraphs: ["We may update this Legal Notice from time to time. The updated version will be posted on this page with a new “Last updated” date."] },
    { title: "Contact", paragraphs: ["For questions about this Legal Notice, contact contact@vireonix.dev or visit https://vireonix.dev. Vireonix operates from Zurich, Switzerland."] },
  ],
};

export const accessibilityDocument: LegalDocument = {
  title: "Accessibility Statement",
  description: "Our commitment to making the Vireonix website accessible and usable for as many people as possible.",
  sections: [
    { title: "Commitment", paragraphs: ["Vireonix is committed to making its website accessible and usable for as many people as possible, including users with disabilities.", "Our goal is to provide a website experience that is clear, readable, keyboard-friendly, responsive, and compatible with modern browsers and assistive technologies."] },
    { title: "Accessibility Target", paragraphs: ["We aim to follow the Web Content Accessibility Guidelines (WCAG) 2.2 Level AA where reasonably possible.", "Accessibility is an ongoing effort, and we continue to improve our website as our services, content, and technology evolve."] },
    { title: "Measures We Take", paragraphs: ["We aim to support accessibility through:"], bullets: ["semantic HTML structure", "clear headings and page sections", "readable text and sufficient spacing", "responsive layouts for mobile, tablet, and desktop", "meaningful alt text for important images", "keyboard-friendly navigation", "visible focus states where possible", "color contrast improvements", "reduced reliance on color alone", "accessible forms and labels where possible", "performance and readability improvements", "reduced-motion considerations for animations"] },
    { title: "Browser & Assistive Technology Compatibility", paragraphs: ["We aim to support current versions of major browsers, including Chrome, Safari, Firefox, and Edge.", "We also aim to improve compatibility with assistive technologies such as screen readers, keyboard navigation tools, and mobile accessibility features."] },
    { title: "Motion & Animations", paragraphs: ["Some parts of the website may include animations or interactive visual effects. Where possible, we aim to respect reduced-motion preferences and provide a cleaner experience for users who prefer less motion."] },
    { title: "Known Limitations", paragraphs: ["Although we try to maintain accessibility, some areas may not yet be fully optimized. Possible limitations may include:"], bullets: ["newly added sections requiring further accessibility review", "third-party tools or embedded content outside our full control", "older images or media requiring improved alternative text", "complex animations that may need fallback improvements"], },
    { title: "Feedback & Assistance", paragraphs: ["If users experience difficulty using our website or need information in an alternative format, they can contact us.", "Helpful details to include:"], bullets: ["the page URL", "device and browser", "the issue experienced", "any assistive technology used", "a short description of what the user was trying to do"] },
    { title: "Contact", paragraphs: ["Email: contact@vireonix.dev", "Website: https://vireonix.dev", "Location: Zurich, Switzerland"] },
  ],
};

export const cookiesDocument: LegalDocument = {
  title: "Cookie Notice",
  description: "Information about cookies and similar technologies that may be used on the Vireonix website.",
  sections: [
    { title: "What Are Cookies?", paragraphs: ["Cookies are small files stored on a user’s device when visiting a website. They help websites function properly, remember preferences, improve performance, and understand how visitors use the site."] },
    { title: "Types of Cookies We May Use", paragraphs: ["Essential Cookies: These are required for the website to work properly, including security, page loading, forms, navigation, and basic functionality.", "Analytics Cookies: These may be used to understand how visitors use the website, which pages are visited, and how the website can be improved.", "Marketing Cookies: These may be used to measure advertising performance or show relevant content, if marketing tools are enabled.", "Preference Cookies: These may be used to remember settings such as language, cookie choices, or display preferences."] },
    { title: "Third-Party Tools", paragraphs: ["We may use third-party services such as hosting, analytics, advertising, embedded content, forms, or performance tools. These services may use cookies or similar technologies according to their own policies."] },
    { title: "Managing Cookies", paragraphs: ["Users can manage or delete cookies through browser settings. If a cookie banner is available on the website, users can update their preferences there.", "Disabling some cookies may affect website functionality."] },
    { title: "Current Cookie Use", paragraphs: ["The Vireonix website currently uses only functionality required to operate and deliver the website experience. We do not currently use advertising cookies or tracking pixels.", "If analytics, tracking pixels, advertising tools, or other non-essential cookies are added later, we will update this Cookie Notice and introduce consent controls where required."] },
    { title: "Changes to This Notice", paragraphs: ["We may update this Cookie Notice from time to time. The updated version will be posted on this page with a new “Last updated” date."] },
    { title: "Contact", paragraphs: ["For questions about cookies, contact contact@vireonix.dev or visit https://vireonix.dev. Vireonix operates from Zurich, Switzerland."] },
  ],
};
